server:
  port: 7001
spring:
  rabbitmq:
    addresses: 192.168.0.110
    port: 5672
    username: guest
    password: guest
    virtual-host: /boot_test
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true